name: Build and Release VT BacBo

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.9'

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=src --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --name="VT-BacBo" --windowed --icon=assets/logo.ico --add-data="assets;assets" src/main.py
      
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v3
      with:
        name: VT-BacBo-Windows
        path: dist/VT-BacBo/

  create-installer:
    name: Create Windows Installer
    runs-on: windows-latest
    needs: build-windows
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: VT-BacBo-Windows
        path: dist/VT-BacBo/
        
    - name: Install Inno Setup
      run: |
        choco install innosetup -y
        
    - name: Create Installer
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer/setup.iss
      
    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Windows-Installer
        path: Output/VT-BacBo-Setup.exe

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test, create-installer]
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Download Installer
      uses: actions/download-artifact@v3
      with:
        name: Windows-Installer
        path: release-assets
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-assets/VT-BacBo-Setup.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run Bandit Security Scan
      run: |
        pip install bandit
        bandit -r src/ -f html -o security-report.html
        
    - name: Upload Security Report
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: security-report.html